export const TableData = [
  {
    pointID: 1,
    pointName: 'پارک ملت',
    category: 'تفریحی',
    status: 'complete',
    image: 'https://via.placeholder.com/150',
    province: 'تهران',
    city: 'تهران',
  },
  {
    pointID: 2,
    pointName: 'مسجد جامع',
    category: 'مذهبی',
    status: 'incomplete',
    image: 'https://via.placeholder.com/150',
    province: 'فارس',
    city: 'شیراز',
  },
  {
    pointID: 3,
    pointName: 'کاخ چهلستون',
    category: 'تاریخی',
    status: 'complete',
    image: 'https://via.placeholder.com/150',
    province: 'اصفهان',
    city: 'اصفهان',
  },
  {
    pointID: 4,
    pointName: 'باغ نادر',
    category: 'تفریحی',
    status: 'complete',
    image: 'https://via.placeholder.com/150',
    province: 'خراسان رضوی',
    city: 'مشهد',
  },
  {
    pointID: 5,
    pointName: 'بازار تبریز',
    category: 'فرهنگی',
    status: 'incomplete',
    image: 'https://via.placeholder.com/150',
    province: 'آذربایجان شرقی',
    city: 'تبریز',
  },
];
