import type { Metadata } from 'next';
import dynamic from 'next/dynamic';

const AuthRoot = dynamic(() => import('@/layout/AuthRoot').then(module => module.default), { ssr: false });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <AuthRoot>{children}</AuthRoot>;
}
