name: Deploy to VM

on:
  push:
    branches:
      - main-action

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Add remote key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan 37.32.24.253 >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          

      - name: Build Docker image
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh ubuntu@37.32.24.253 << 'EOF'
            cd /home/ubuntu/bznbrbAdminNew
            git fetch origin
            git reset --hard origin/main-action
            git pull origin main-action
            sudo docker build -t bznFront .

          EOF
